version: '3.3'

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'waruniverse'
            MYSQL_ROOT_PASSWORD: 'rootroot'
        ports:
            -   '3306:3306'
        expose:
            -   '3306'
        volumes:
            -   mysql:/var/lib/mysql
volumes:
    mysql: